language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy3.5"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y gtk+3.0 libgirepository1.0-dev
install:
  - pip install -r requirements.txt --user
# command to run tests
script: python -m unittest discover .