language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy3.5"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y gobject-introspection
install:
  - pip install -r requirements.txt
# command to run tests
script: python -m unittest discover .